name: Divonico - Spring

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
          
    - name: Deploy na EC2
      run: |
           echo "${{secrets.KEY_EC2_E}}" >private_key && chmod 400 private_key
           ssh -i "UboiKey.pem" ubuntu@ec2-3-82-21-179.compute-1.amazonaws.com "
                     cd /home/ubuntu/POC &&
                     git pull &&
                     mvn clean package -DskipTests &&
                     ./executar.sh "
                     
